# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  default_executor:
    docker:
      - image: cimg/node:18.9
    working_directory: ~/repo

jobs:
  deploy:
    executor: default_executor
    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install rsync
      - run: npm ci

      - run: echo "No tests yet"

      - add_ssh_keys:
          fingerprints:
            - "c7:64:14:51:f8:85:7a:2c:37:64:a2:8e:6b:44:42:c4"
      - run: ssh-keyscan -H $PRODUCTION_SERVER_HOST >> ~/.ssh/known_hosts

      - run: npx shipit production deploy

workflows:
  version: 2

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
